# Generated by Django 5.2.13 on 2026-04-20 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0003_patrollog_latitude_patrollog_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboard_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guard', 'Guard'), ('client', 'Client')], max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('guard_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_duty', 'On duty')], default='', max_length=16)),
                ('onboarding_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=64)),
                ('registration_notes', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('phone_country_code', models.CharField(blank=True, max_length=8)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='passports/')),
                ('linked_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_guards', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guards', to='operations.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
