# Generated by Django 5.2.13 on 2026-04-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_address',
            field=models.TextField(blank=True),
        ),
    ]
