# Generated by Django 5.2.13 on 2026-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_guardlocationping'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrollog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
