# Generated by Django 5.2.13 on 2026-04-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_patrollog_latitude_patrollog_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='reportentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportentry',
            name='filters_json',
            field=models.TextField(blank=True),
        ),
    ]
