from django.urls import path

from accounts import views as account_views
from operations import views

urlpatterns = [
    path('login/', account_views.login),
    path('company-signup/', account_views.company_signup),
    path('dashboard-invite/', account_views.dashboard_invite_create),
    path('dashboard-invite-status/', account_views.dashboard_invite_status),
    path('dashboard-invite-accept/', account_views.dashboard_invite_accept),
    path('guard-register/', account_views.guard_register),
    path('guard-verify-email/', account_views.guard_verify_email),
    path('guard-registration-status/', account_views.guard_registration_status),
    path('guard-link/', account_views.guard_link),
    path('guard-approve/', account_views.guard_approve),
    path('guard-reject/', account_views.guard_reject),
    path('guards/', views.guards_list),
    path('sites/', views.sites_list),
    path('checkpoints/', views.checkpoints_list),
    path('checkpoints-create/', views.checkpoints_create),
    path('checkpoints/<str:checkpoint_id>/', views.checkpoint_detail),
    path('alerts/', views.alerts_list),
    path('alerts/<str:alert_id>/status/', views.alert_status_update),
    path('shifts/', views.shifts_list),
    path('shifts-create/', views.shifts_create),
    path('shifts/<str:shift_id>/', views.shift_detail),
    path('assigned-checkpoints/', views.assigned_checkpoints),
    path('patrol-logs/', views.patrol_logs_list),
    path('incidents/', views.incidents_list),
    path('incidents/<str:incident_id>/status/', views.incident_status_update),
    path('reports/', views.reports_list),
    path('reports-generate/', views.reports_generate),
    path('reports-download/<str:report_id>/', views.reports_download),
    path('dashboard/', views.dashboard_summary),
    path('start-shift/', views.start_shift),
    path('end-shift/', views.end_shift),
    path('scan-checkpoint/', views.scan_checkpoint),
    path('location-pings/', views.location_pings_list),
    path('submit-location-pings/', views.submit_location_pings),
    path('patrol-evidence/', views.patrol_evidence),
    path('report-incident/', views.report_incident),
    path('panic-alert/', views.panic_alert),
    path('company-settings/', account_views.company_settings),
]
